server:
  port: 8087


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non-contextual-creation: true
logging:
  level:
    com.ead: TRACE
    root: DEBUG